### ISSUE TITLE
Question: Why ignore any errors

### ISSUE THREAD

**Issue by Thiago-Mota-Santos** [Satsails/Satsails#21]
I reviewing the code and i have some question, i will list it below:

- [ ] Why ignore any errors in the catch?
   lib/providers/boltz_provider.dart
![image](https://github.com/user-attachments/assets/0ae28f70-fa94-45d6-9ca5-b3e994b2a7f7)
-  [ ] - Hardcoded address is danger:    
![image](https://github.com/user-attachments/assets/d95ce69d-fe44-4853-8cd0-cd7bbfdc30ad)

**Comment by Saleciani** [comment]
Hey

The errors are ignored because it runs in a loop, where if the claim fails, we want to ignore keep the claim data.

I know it isn't the best, but I am currently rebuilding this part, for a native implementation of Lightning, so this should be all cleaned up soon.

Those are not addresses but rather asset ids from the liquid network.
Needs refactoring, but besides them being built in the library I do not think they should be an env var.

**Comment by Saleciani** [comment]
Overall the codebase needs some refactoring, v1.1 should be a refactoring release with bug fixes
